name: "Release Announcement Action"
description: "automatically comment on released pull requests and linked issues"
author: "remix-run"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  color: "purple"
  icon: "tag"
inputs:
  GH_TOKEN:
    description: "The GitHub token to use for interacting with the GitHub API - needed for gh commands"
    required: false
    default: ${{ github.token }}
  GITHUB_REPOSITORY:
    description: "The GitHub repository - needed for creating and logging urls"
    required: false
    default: ${{ github.repository }}
  DIRECTORY_TO_CHECK:
    description: "The directory to check for release files"
    required: false
    default: "./"
  DRY_RUN:
    description: "Whether to actually comment on PRs/issues or not"
    required: false
    default: "false"
  PACKAGE_NAME:
    description: "The package name to follow - useful in monorepos to filter git tags (e.g. `@remix-run/v1-route-convention`, or `remix`)"
    required: false
  INCLUDE_NIGHTLY:
    description: "Whether to include nightly releases or not (only applies when `PACKAGE_TAG_PREFIX` is set)"
    required: true
    default: "true"
  PR_LABELS_TO_REMOVE:
    description: "Any labels to remove when commenting on Pull Requests about STABLE releases - in Remix we apply `awaiting release` to pulls that have been merged but not released"
    required: false
  ISSUE_LABELS_TO_REMOVE:
    description: "Any labels to remove when commenting on and closing issues about STABLE releases"
    required: false
